export const HOME_PAGE_ACTION_TYPES = {
  TOGGLE_ADD_EXPENSE_MODAL: "TOGGLE_ADD_EXPENSE_MODAL",
  TOGGLE_EDIT_EXPENSE_MODAL: "TOGGLE_EDIT_EXPENSE_MODAL",
  SUBMIT_EDIT_EXPENSE: "SUBMIT_EDIT_EXPENSE",
  RESET_FILTER: "RESET_FILTER",
  ADD_FILTER: "ADD_FILTER",
  REMOVE_FILTER: "REMOVE_FILTER",
}
